:header
Sviatoslav-lion/project-GREEN_FARM_12 pull request #11
Opened 2024-10-18 18:24 UTC by R220V

Обов"язково вадалити  background-color: #576f35; в стилях .header-container, після МЕРЧУ 2секціЇ, інакше білі шрифти-іконки зараз  можуть злитися з білим бекграундом.
І залишити (скопіювати) мій спрайт.

2024-10-18 19:29 UTC, Sviatoslav-lion requested changes
Вітаю. 
1. Посилання меню не мають якірних посилань. Згідно ТЗ вони мають бути.
2. Згідно макету під header ом фон hero секції. Header має бути зверху над hero. Фон при цьому має бути прозорий.

2024-10-20 10:01 UTC, Sviatoslav-lion requested changes
Привіт.
Потрібно домовитись між собою стосовно ID для посилань, та внести зміни в цю частинку.
Внести інші зміни по коду.
Підтягнути в цю гілку зміни з main
І ще стосовно всієї секції, мені здалось вона не висить над hero, чи може я помиляюсь?
В цілому все круто! дизайн класний!

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/css/1_header.css
>      padding-bottom: 16px;
Повторюються, в menu item вже задані

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/partials/1_header.html
> +              <a class="menu-link" href="#3_how_it_works"/>How It Works</a>
Посилання не працюють. Некоректний ID

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/partials/1_header.html
> +              <a class="menu-link" href="#5_vegetables"/>Vegetables</a>
Посилання не працюють. Некоректний ID

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/partials/1_header.html
> +              <a class="menu-link" href="#6_reviews">Reviews</a>
Посилання не працюють. Некоректний ID

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/css/1_header.css
>      letter-spacing: -0.02em;
@media screen and (min-width: 1280px) {
  .menu-item {
    font-weight: 500;
    font-size: 16px;
    line-height: 1.25;
    letter-spacing: -0.02em;
Ці стилі повторюються з base.css, потрібно повтори прибрати

2024-10-20 10:01 UTC, Sviatoslav-lion commented on src/css/1_header.css
>      border-radius: 30px;
border: none;
border-radius: 30px;
font-weight: 600;
letter-spacing: -0.01em;
text-transform: uppercase;
Ці атрибути є повторами з базового стилю base.css

2024-10-21 00:16 UTC, R220V commented
Намагався все виправити.  Падінги з 16 збив на 13 - так потрібно для легшого тапання по лінках.  Добавив в дизайн планшета та мобілки хедер з  фоном, а то бургера зовсім не видно. Для дуету з ХЕРО довелось трохи добавити коду та стилів. Після злиття їх потрібно видалити.  В мене все працює - все ОК.  Сьогодні буду після 18:00 - Робота!

2024-10-21 16:57 UTC, Sviatoslav-lion approved these changes

2024-10-21 16:57 UTC, merged