How works
Sviatoslav-lion/project-GREEN_FARM_12 pull request #15
Opened 2024-10-19 17:34 UTC by Lobash1

2024-10-19 21:09 UTC, Sviatoslav-lion requested changes
Привіт.
В розмірі екрану 1280px ліворуч є полоска зеленого, за макетом вся ліва частина бордова.
В розмірі екрану 1279px верхня частина секції має бути бордовою від лівого краю екрана до правого.
Те саме в розмірі 766px.
В мобільній версії є розбіжності з макетом
1.  padding в блоках списку
2.  розмір шрифту та line-hight
3.  відстань між блоками

2024-10-19 21:09 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +.section-base {
Атрибути базових класів не можна змінювати, через те що це чіпляє весь проект і зміни відбудуться у всіх секціях. Потрібно створити свій клас та додати його додатково поруч з базовим до тегу.

2024-10-19 21:09 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +    padding-left: 30px;
Padding: 24px;

2024-10-20 10:06 UTC, Lobash1 commented on src/css/3_how_it_works.css
> +    padding-left: 30px;
виправила

2024-10-20 11:52 UTC, Sviatoslav-lion requested changes
Привіт
В десктопній версії лівий бордовий фон має розтягуватись до лівого краю
В мобільній версії контейнера списку різного розміру по висоті і не відповідають макету
Також є повтори стилів шрифтів з базового стиля з base.css, повтори потрібно прибрати.
Також продивись будь ласка чи є повтори між медіа запитами

2024-10-20 20:14 UTC, Sviatoslav-lion reviewed
Привіт.
Уважно передивись в дев тулзах свою частинку сторінки

2024-10-20 20:19 UTC, Sviatoslav-lion requested changes
Привіт.
1. Мобільна версія не за макетом.
Уважно передивись в дев тулзах свою частинку сторінки звертай увагу на текст, скільки строк тексту, під яким словом розташоване останнє слово в рядку, які маржини між частинами, скільки пікселів, чи є властивості в тексті що повторяються з інших частин css або медіа запитів.
Все це порівнюй з макетом та виправляй. 
Посилання на макет
https://www.figma.com/design/ObvvH4JjCuw8gBzYmiLIII/GreenHarvest?node-id=0-1&node-type=canvas&t=QNCBhG997cx5I6RY-0

2024-10-21 11:26 UTC, Sviatoslav-lion requested changes
Привіт
Потрібно трохи доробити та внести вказані зміни

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/partials/3_how_it_works.html
> +    <div class="container how-it-works-container">
видали клас container

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +        width: 630px;
змінити на 650

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +    .works-text {
додати      letter-spacing: 0;

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +
додати клас
 .how-item:last-child {
    margin-bottom: 0;
}

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +    .how-item {
додати      padding: 12px 25px;

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +
додати клас 
.padding_risght_plus {
        padding-right: 0px;
    }

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +
Додати клас 
.padding_risght_plus {
    padding-right: 59px;
}

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/partials/3_how_it_works.html
> +                    <li class="how-item">
додати клас padding_risght_plus

2024-10-21 11:26 UTC, Sviatoslav-lion commented on src/css/3_how_it_works.css
> +
додати
  .works-item-text {
        font-size: 16px; 
    }

2024-10-21 19:13 UTC, Sviatoslav-lion approved these changes
Perfecto!

2024-10-21 19:14 UTC, merged