add your_order.html and your_order.css files
Sviatoslav-lion/project-GREEN_FARM_12 pull request #6
Opened 2024-10-18 08:53 UTC by NatalyaMalenko

2024-10-19 22:07 UTC, Sviatoslav-lion requested changes
Привіт.
Потрібно дещо виправити:
1. Контент має бути відцентрованим. 
2. Фон має бути на всю секцію.
Форма
1. placeholder спозиціонований не за макетом.
2. при фокусі синій бордер затуляє зелену та червону підсвітку. Думаю потрібно його прибрати або змінити колір та розмір
3. в полі коментаря при фокусі слово Comment потрібно прибирати, бо воно заважає набирати коментар.

2024-10-20 14:17 UTC, NatalyaMalenko commented
Я виправила помилки, перевіряй.

2024-10-20 15:40 UTC, Sviatoslav-lion requested changes
Привіт. 
Потрібно зробити зміни

2024-10-20 15:40 UTC, Sviatoslav-lion commented on src/css/7_your_order.css
> +  }
текст не за макетом. Потрібно обнулити letter-spacing

2024-10-20 15:40 UTC, Sviatoslav-lion commented on src/css/7_your_order.css
> +}
Не можна змінювати базові стилі. Потрібно створювати свій і додавати його поруч з базовим

2024-10-20 15:40 UTC, Sviatoslav-lion commented on src/css/7_your_order.css
> +  }
це базовий стиль. не можна його змінювати

2024-10-20 17:00 UTC, NatalyaMalenko commented on src/css/7_your_order.css
> +  }
done

2024-10-20 17:00 UTC, NatalyaMalenko commented on src/css/7_your_order.css
> +}
done

2024-10-20 17:00 UTC, NatalyaMalenko commented on src/css/7_your_order.css
> +  }
done

2024-10-20 19:17 UTC, Sviatoslav-lion approved these changes

2024-10-20 19:17 UTC, merged